#!/bin/bash
#
#
### BEGIN INIT INFO
# Provides: MPTomcatProxy
# Required-Start: $network $syslog
# Required-Stop: $network $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Description: MacPatch Tomcat Startup Script
# Short-Description: start and stop tomcat
### END INIT INFO

. /lib/lsb/init-functions

cd /
umask 022
 
## Source function library.
#. /etc/rc.d/init.d/functions
if [ -d  "/usr/lib/jvm/default-java" ]; then
	export JAVA_HOME=/usr/lib/jvm/default-java
elif [ -d  "/usr/lib/jvm/java" ]; then
	export JAVA_HOME=/usr/lib/jvm/java
fi	
export PATH=$JAVA_HOME/bin:$PATH
TOMCAT_HOME=/Library/MacPatch/Server/tomcat-mpproxy
SHUTDOWN_WAIT=20
 
start() 
{
	# Start tomcat
	echo "Starting tomcat"
	ulimit -n 100000
	umask 022
	/bin/su -p -s /bin/sh www-data $TOMCAT_HOME/bin/startup.sh
}
 
stop() 
{
	# Stop tomcat
	echo "Stoping Tomcat"
	/bin/su -p -s /bin/sh www-data $TOMCAT_HOME/bin/shutdown.sh
}
 
case $1 in
start)
	start
	;;
stop)
	stop
	;;
restart)
	stop
	start
	;;
*) 
	echo "Run as $0 <start|stop|restart>"
	exit 1
	;; 
esac
exit 0
