#!/bin/bash	

# ***************************************************************************************
# PreFlight Script for MacPatch Client Updater Installer
# ver 2.0
# Created By Charles Heizer @ LLNL
# 
#
# ***************************************************************************************

systemVersion=`/usr/bin/sw_vers -productVersion`
majorVer=`echo $systemVersion | cut -d . -f 1,2  | sed 's/\.//g'`
minorVer=`echo $systemVersion | cut -d . -f 2`
buildVer=`echo $systemVersion | cut -d . -f 3`

dts=`date +%Y%m%d%H%M%S`

if [ -e "/Library/LaunchDaemons/gov.llnl.mp.agentUpdater.plist" ]; then
	
	/bin/launchctl stop gov.llnl.mp.agentUpdater
	sleep 1
	/bin/launchctl unload -w /Library/LaunchDaemons/gov.llnl.mp.agentUpdater.plist
	sleep 1
	
fi	

exit 0