"""00010 - Base

Revision ID: 100010
Revises: 100009
Create Date: 2020-04-10

"""

# revision identifiers, used by Alembic.
revision = '100010'
down_revision = '100009'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


def upgrade():
	### commands auto generated by Alembic - please adjust! ###

	op.create_table('mdm_intune_devices',
		sa.Column('rid', sa.BigInteger(), nullable=False, autoincrement=True),
		sa.Column('id', sa.String(length=255), server_default='', nullable=False),
		sa.Column('userId', sa.String(length=255), server_default='', nullable=False),
		sa.Column('deviceName', sa.String(length=255), server_default='', nullable=True),
		sa.Column('managedDeviceOwnerType', sa.String(length=255), server_default='', nullable=True),
		sa.Column('enrolledDateTime', sa.DateTime(), server_default='1970-01-01 00:00:00', nullable=True),
		sa.Column('lastSyncDateTime', sa.DateTime(), server_default='1970-01-01 00:00:00', nullable=True),
		sa.Column('operatingSystem', sa.String(length=255), server_default='', nullable=True),
		sa.Column('complianceState', sa.String(length=255), server_default='', nullable=True),
		sa.Column('jailBroken', sa.BOOLEAN(), server_default=False, nullable=True),
		sa.Column('managementAgent', sa.String(length=255), server_default='', nullable=True),
		sa.Column('osVersion', sa.String(length=255), server_default='', nullable=True),
		sa.Column('easActivated', sa.BOOLEAN(), server_default=False, nullable=True),
		sa.Column('easDeviceId', sa.String(length=255), server_default='', nullable=True),
		sa.Column('easActivationDateTime', sa.DateTime(), server_default='1970-01-01 00:00:00', nullable=True),
		sa.Column('azureADRegistered', sa.BOOLEAN(), server_default=False, nullable=True),
		sa.Column('deviceEnrollmentType', sa.String(length=255), server_default='', nullable=True),
		sa.Column('activationLockBypassCode', sa.String(length=255), server_default='', nullable=True),
		sa.Column('emailAddress', sa.String(length=255), server_default='', nullable=True),
		sa.Column('azureADDeviceId', sa.String(length=255), server_default='', nullable=True),
		sa.Column('deviceRegistrationState', sa.String(length=255), server_default='', nullable=True),
		sa.Column('deviceCategoryDisplayName', sa.String(length=255), server_default='', nullable=True),
		sa.Column('isSupervised', sa.BOOLEAN(), server_default=False, nullable=True),
		sa.Column('exchangeLastSuccessfulSyncDateTime', sa.DateTime(), server_default='1970-01-01 00:00:00', nullable=True),
		sa.Column('exchangeAccessState', sa.String(length=255), server_default='', nullable=True),
		sa.Column('exchangeAccessStateReason', sa.String(length=255), server_default='', nullable=True),
		sa.Column('remoteAssistanceSessionUrl', sa.String(length=255), server_default='', nullable=True),
		sa.Column('remoteAssistanceSessionErrorDetails', sa.String(length=255), server_default='', nullable=True),
		sa.Column('isEncrypted', sa.BOOLEAN(), server_default=False, nullable=True),
		sa.Column('userPrincipalName', sa.String(length=255), server_default='', nullable=True),
		sa.Column('model', sa.String(length=255), server_default='', nullable=True),
		sa.Column('manufacturer', sa.String(length=255), server_default='', nullable=True),
		sa.Column('imei', sa.String(length=255), server_default='', nullable=True),
		sa.Column('complianceGracePeriodExpirationDateTime', sa.DateTime(), server_default='1970-01-01 00:00:00', nullable=True),
		sa.Column('serialNumber', sa.String(length=255), server_default='', nullable=True),
		sa.Column('phoneNumber', sa.String(length=255), server_default='', nullable=True),
		sa.Column('androidSecurityPatchLevel', sa.String(length=255), server_default='', nullable=True),
		sa.Column('userDisplayName', sa.String(length=255), server_default='', nullable=True),
		sa.Column('configurationManagerClientEnabledFeatures', sa.String(length=255), server_default='', nullable=True),
		sa.Column('wiFiMacAddress', sa.String(length=255), server_default='', nullable=True),
		sa.Column('deviceHealthAttestationState', sa.String(length=255), server_default='', nullable=True),
		sa.Column('subscriberCarrier', sa.String(length=255), server_default='', nullable=True),
		sa.Column('meid', sa.String(length=255), server_default='', nullable=True),
		sa.Column('totalStorageSpaceInBytes', sa.BigInteger(), server_default=0, nullable=True),
		sa.Column('freeStorageSpaceInBytes', sa.BigInteger(), server_default=0, nullable=True),
		sa.Column('managedDeviceName', sa.String(length=255), server_default='', nullable=True),
		sa.Column('partnerReportedThreatState', sa.String(length=255), server_default='', nullable=True),
		sa.PrimaryKeyConstraint('rid')
	)

	op.create_index(op.f('ix_mdm_intune_devices_id'), 'mdm_intune_devices', ['id'], unique=False)
	op.create_index(op.f('ix_mdm_intune_devices_userid'), 'mdm_intune_devices', ['userId'], unique=False)


	### end Alembic commands ###


def downgrade():
	### commands auto generated by Alembic - please adjust! ###

	op.drop_index(op.f('ix_mdm_intune_devices_id'), table_name='mdm_intune_devices')
	op.drop_index(op.f('ix_mdm_intune_devices_userid'), table_name='mdm_intune_devices')
	op.drop_table('mdm_intune_devices')

	### end Alembic commands ###

