"""00011 - Base

Revision ID: 100011
Revises: 100010
Create Date: 2020-09-08

"""

# revision identifiers, used by Alembic.
revision = '100011	'
down_revision = '100010'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


def upgrade():
	### commands auto generated by Alembic - please adjust! ###

	### end Alembic commands ###
	u_qstr1 = "ALTER TABLE `mp_software` ADD COLUMN `sw_useS3` int(1) NULL DEFAULT 0 AFTER `sw_hash`;"
	op.execute(u_qstr1)

def downgrade():
	### commands auto generated by Alembic - please adjust! ###

	### end Alembic commands ###
	d_qstr1 = "ALTER TABLE `mp_software` DROP COLUMN `sw_useS3`;"
	op.execute(d_qstr1)