"""0006 - MP 3.3.0 Schema additions

Revision ID: 100006
Revises: 100005
Create Date: 2019-06-19

"""

# revision identifiers, used by Alembic.
revision = '100006'
down_revision = '100005'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


def upgrade():
	### commands auto generated by Alembic - please adjust! ###
	op.create_table('mp_software_restrictions',
		sa.Column('rid', sa.BigInteger(), nullable=False, autoincrement=True),
		sa.Column('appID', sa.String(length=50), server_default='', nullable=False),
		sa.Column('bundleID', sa.String(length=50), server_default='', nullable=True),
		sa.Column('displayName', sa.String(length=50), server_default='', nullable=False),
		sa.Column('processName', sa.String(length=50), server_default='', nullable=False),
		sa.Column('message', mysql.TEXT(), nullable=True),
		sa.Column('killProc', mysql.INTEGER(display_width=1, unsigned=True), server_default='1',nullable=True),
		sa.Column('sendEmail', mysql.INTEGER(display_width=1, unsigned=True), server_default='0',nullable=True),
		sa.Column('enabled', mysql.INTEGER(display_width=1, unsigned=True), server_default='0',nullable=True),
		sa.Column('isglobal', mysql.INTEGER(display_width=1, unsigned=True), server_default='0',nullable=True),
		sa.Column('mdate', sa.DateTime(), server_default='1970-01-01 00:00:00', nullable=True),
		sa.PrimaryKeyConstraint('rid')
	)
	op.create_index(op.f('ix_mp_software_restrictions_appid'), 'mp_software_restrictions', ['appID'], unique=False)

	op.create_table('mp_client_group_software_restrictions',
		sa.Column('rid', sa.BigInteger(), nullable=False, autoincrement=True),
		sa.Column('group_id', sa.String(length=50), server_default='', nullable=False),
		sa.Column('appID', sa.String(length=50), server_default='', nullable=False),
		sa.Column('enabled', mysql.INTEGER(display_width=1, unsigned=True), server_default='0'),
		sa.PrimaryKeyConstraint('rid')
	)
	op.create_index(op.f('ix_mp_client_group_software_restrictions_appid'), 'mp_client_group_software_restrictions', ['appID'], unique=False)

def downgrade():
	### commands auto generated by Alembic - please adjust! ###
	op.drop_index(op.f('ix_mp_software_restrictions_appid'), table_name='mp_software_restrictions')
	op.drop_table('mp_software_restrictions')

	op.drop_index(op.f('ix_mp_software_restrictions_appid'), table_name='mp_client_group_software_restrictions')
	op.drop_table('mp_client_group_software_restrictions')
