"""0004 - MP 3.1.0 Schema additions

Revision ID: 100004
Revises: 100003
Create Date: 2017-03-28

"""

# revision identifiers, used by Alembic.
revision = '100004'
down_revision = '100003'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


def upgrade():
	### commands auto generated by Alembic - please adjust! ###

	op.create_table('mp_client_group_software',
		sa.Column('rid', sa.BigInteger(), nullable=False, autoincrement=True),
		sa.Column('group_id', sa.String(length=50), nullable=False),
		sa.Column('tuuid', sa.String(length=50), nullable=False),
		sa.PrimaryKeyConstraint('rid')
	)
	op.create_index(op.f('ix_mp_client_group_software_tuuid'), 'mp_client_group_software', ['tuuid'], unique=False)
	op.create_index(op.f('ix_mp_client_group_software_group_id'), 'mp_client_group_software', ['group_id'], unique=False)

def downgrade():
	### commands auto generated by Alembic - please adjust! ###
	op.drop_index(op.f('ix_mp_client_group_software_tuuid'), table_name='mp_client_group_software')
	op.drop_index(op.f('ix_mp_client_group_software_group_id'), table_name='mp_client_group_software')
	op.drop_table('mp_client_group_software')

