"""0009 - Base

Revision ID: 100009
Revises: 100008
Create Date: 2020-02-13

"""

# revision identifiers, used by Alembic.
revision = '100009'
down_revision = '100008'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


def upgrade():
	### commands auto generated by Alembic - please adjust! ###

	op.create_table('mp_agent_installs',
					sa.Column('rid', sa.BigInteger(), nullable=False, autoincrement=True),
					sa.Column('cuuid', sa.String(length=50), server_default='', nullable=False),
					sa.Column('install_date', sa.DateTime(), server_default='1970-01-01 00:00:00', nullable=True),
					sa.Column('agent_ver', sa.String(length=255), server_default='', nullable=False),
					sa.PrimaryKeyConstraint('rid')
					)

	op.create_index(op.f('ix_mp_agent_installs_cuuid'), 'mp_agent_installs', ['cuuid'], unique=False)

	### end Alembic commands ###
	u_qstr1 = "ALTER TABLE `mp_clients` ADD COLUMN `depEnrolled` text NULL AFTER `hasPausedPatching`;"
	op.execute(u_qstr1)

	u_qstr2 = "ALTER TABLE `mp_clients` ADD COLUMN `mdmEnrolled` text NULL AFTER `depEnrolled`;"
	op.execute(u_qstr2)

	u_qstr3="ALTER TABLE `mp_software` ADD COLUMN `sw_app_path` text NULL AFTER `sReboot`;"
	op.execute(u_qstr3)


def downgrade():
	### commands auto generated by Alembic - please adjust! ###

	op.drop_index(op.f('ix_mp_agent_installs_cuuid'), table_name='mp_agent_installs')
	op.drop_table('mp_agent_installs')

	### end Alembic commands ###
	d_qstr1 = "ALTER TABLE `mp_software` DROP COLUMN `sw_app_path`;"
	op.execute(d_qstr1)

	d_qstr1 = "ALTER TABLE `mp_clients` DROP COLUMN `depEnrolled`;"
	op.execute(d_qstr1)

	d_qstr1 = "ALTER TABLE `mp_clients` DROP COLUMN `mdmEnrolled`;"
	op.execute(d_qstr1)

