#!/bin/bash

# ***************************************************************************************
# PostFlight Script for MacPatch Client Updater Installer
# ver 2.0
# Created By Charles Heizer @ LLNL
#
# ***************************************************************************************

# Create .mpUpdate
if [ ! -d "/Users/Shared/.mpUpdate" ]; then
	mkdir "/Users/Shared/.mpUpdate"
fi

# Set ownership of .mpUpdate
chmod 777 "/Users/Shared/.mpUpdate"
chown root:admin "/Users/Shared/.mpUpdate"

if [ -e "/Library/LaunchDaemons/gov.llnl.mp.agentUpdater.plist" ]; then
	# Launch the swupd daemon...
	/bin/launchctl load -wF /Library/LaunchDaemons/gov.llnl.mp.agentUpdater.plist
	/bin/sleep 2
fi

# Copy Backup Log Files Back To Updater Logs Dir
if [ -d "/Library/MacPatch/.logs" ]; then
	FILES="/Library/MacPatch/.logs/MPAgentUp2Date*"
	for f in $FILES
	do
		mv "$f" "/Library/MacPatch/Updater/Logs/${f}"
	done
fi

exit 0;