#!/bin/sh

# ***************************************************************************************
# PreFlight Script for MacPatch Server Installer
# ver 1.0
# Created By Charles Heizer
# LLNL
#
#
# ***************************************************************************************

systemVersion=`/usr/bin/sw_vers -productVersion`
majorVer=`echo $systemVersion | cut -d . -f 1,2  | sed 's/\.//g'`
minorVer=`echo $systemVersion | cut -d . -f 2`
buildVer=`echo $systemVersion | cut -d . -f 3`

# Script Parent Dir Path
SRC=$(cd $(dirname "$0"); pwd)

MPBaseDir="/Library/MacPatch"
MPServerDir="/Library/MacPatch/Server"
MPContentDir="/Library/MacPatch/Content"
dts=`date +%Y%m%d%H%M%S`

# Unload All Services if Server is installed
if [ -f "${MPServerDir}/conf/scripts/Setup/StartServices.py" ] ; then
	${MPServerDir}/conf/scripts/Setup/StartServices.py --unload All
fi

# Rename current dirs
if [ -d "${MPServerDir}" ]; then
	mv "${MPServerDir}" "${MPServerDir}.$dts"
fi

if [ -d "${MPContentDir}" ]; then
	mv "${MPContentDir}" "${MPContentDir}.$dts"
fi

exit 0