#ifndef MK1MF_BUILD
    /* auto-generated by util/mkbuildinf.pl for crypto/cversion.c */
    #define CFLAGS cflags
    /*
     * Generate CFLAGS as an array of individual characters. This is a
     * workaround for the situation where CFLAGS gets too long for a C90 string
     * literal
     */
    static const char cflags[] = {
        'c','o','m','p','i','l','e','r',':',' ','c','c',' ','-','I','.',' ','-',
        'I','.','.',' ','-','I','.','.','/','i','n','c','l','u','d','e',' ',' ',
        '-','D','_','D','A','R','W','I','N','_','C','_','S','O','U','R','C','E',
        ' ','-','U','O','P','E','N','S','S','L','_','B','N','_','A','S','M','_',
        'P','A','R','T','_','W','O','R','D','S',' ','-','a','r','c','h',' ','x',
        '8','6','_','6','4',' ','-','i','s','y','s','r','o','o','t',' ','/','A',
        'p','p','l','i','c','a','t','i','o','n','s','/','X','c','o','d','e','.',
        'a','p','p','/','C','o','n','t','e','n','t','s','/','D','e','v','e','l',
        'o','p','e','r','/','P','l','a','t','f','o','r','m','s','/','M','a','c',
        'O','S','X','.','p','l','a','t','f','o','r','m','/','D','e','v','e','l',
        'o','p','e','r','/','S','D','K','s','/','M','a','c','O','S','X','1','0',
        '.','1','1','.','s','d','k',' ','-','W','n','o','-','u','n','u','s','e',
        'd','-','v','a','l','u','e',' ','-','W','n','o','-','p','a','r','e','n',
        't','h','e','s','e','s','\0'
    };
    #define PLATFORM "platform: darwin-i386-cc"
    #define DATE "built on: Wed Jan 27 11:23:41 2016"
#endif
