"""0002a - Base

Revision ID:
Revises: 100002
Create Date: 2018-04-18

"""

# revision identifiers, used by Alembic.
revision = '100002a'
down_revision = '100002'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


def upgrade():
	### commands auto generated by Alembic - please adjust! ###

	### end Alembic commands ###
	u_qstr1="ALTER TABLE `apple_patches_mp_additions` ADD COLUMN `user_install` int(1) NULL DEFAULT AFTER `osver_support`;"
	op.execute(u_qstr1)


def downgrade():
	### commands auto generated by Alembic - please adjust! ###

	### end Alembic commands ###
	d_qstr1 = "ALTER TABLE `apple_patches_mp_additions` DROP COLUMN `user_install`;"
	op.execute(d_qstr1)
