"""0006a - Base

Revision ID: 100006a
Revises: 100006
Create Date: 2018-04-18

"""

# revision identifiers, used by Alembic.
revision = '100006a'
down_revision = '100006'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


def upgrade():
	### commands auto generated by Alembic - please adjust! ###

	### end Alembic commands ###
	u_qstr1="ALTER TABLE `mp_group_config` ADD COLUMN `restrictions_version` bigint(255) NULL DEFAULT 0 AFTER `tasks_version`;"
	op.execute(u_qstr1)


def downgrade():
	### commands auto generated by Alembic - please adjust! ###

	### end Alembic commands ###
	d_qstr1 = "ALTER TABLE `mp_group_config` DROP COLUMN `restrictions_version`;"
	op.execute(d_qstr1)
