"""00011 - Base

Revision ID: 100013
Revises: 100010
Create Date: 2020-09-08

"""

# revision identifiers, used by Alembic.
revision = '100016'
down_revision = '100015'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


def upgrade():
	### commands auto generated by Alembic - please adjust! ###

	op.create_table('mp_inventory',
		sa.Column('rid', sa.BigInteger(), nullable=False, autoincrement=True),
		sa.Column('cuuid', sa.String(length=50), nullable=False),
		sa.Column('table', sa.String(length=255), nullable=False),
		sa.Column('jdata', sa.JSON, nullable=False),
		sa.Column('mdate', sa.DateTime(), server_default='1970-01-01 00:00:00', nullable=True),
		sa.PrimaryKeyConstraint('rid')
	)
	op.create_index(op.f('ix_mp_inventory_cuuid'), 'mp_inventory', ['cuuid'], unique=False)

	op.create_table('mp_inventory_client_keys',
		sa.Column('rid', sa.BigInteger(), nullable=False, autoincrement=True),
		sa.Column('cuuid', sa.String(length=50), nullable=False),
		sa.Column('table', sa.String(length=255), nullable=False),
		sa.Column('jdata', sa.JSON, nullable=False),
		sa.Column('mdate', sa.DateTime(), server_default='1970-01-01 00:00:00', nullable=True),
		sa.PrimaryKeyConstraint('rid')
	)
	op.create_index(op.f('ix_mp_inventory_client_keys_cuuid'), 'mp_inventory_client_keys', ['cuuid'], unique=False)

	op.create_table('mp_inventory_keys',
		sa.Column('rid', sa.BigInteger(), nullable=False, autoincrement=True),
		sa.Column('table', sa.String(length=255), nullable=False),
		sa.Column('keys', sa.Text, nullable=True),
		sa.Column('key_count', sa.Integer, nullable=True),
		sa.Column('mdate', sa.DateTime(), server_default='1970-01-01 00:00:00', nullable=True),
		sa.PrimaryKeyConstraint('rid')
	)
	op.create_index(op.f('ix_mp_inventory_keys_table'), 'mp_inventory_keys', ['table'], unique=False)

	### end Alembic commands ###


def downgrade():
	### commands auto generated by Alembic - please adjust! ###
	op.drop_index(op.f('ix_mp_inventory_keys_table'), table_name='mp_inventory_keys')
	op.drop_table('mp_inventory_keys')

	op.drop_index(op.f('ix_mp_inventory_client_keys_cuuid'), table_name='mp_inventory_client_keys')
	op.drop_table('mp_inventory_client_keys')

	op.drop_index(op.f('ix_mp_inventory_cuuid'), table_name='mp_inventory')
	op.drop_table('mp_inventory')

	### end Alembic commands ###
