#!/usr/bin/env python

'''
 Copyright (c) 2013, Lawrence Livermore National Security, LLC.
 Produced at the Lawrence Livermore National Laboratory (cf, DISCLAIMER).
 Written by Charles Heizer <heizer1 at llnl.gov>.
 LLNL-CODE-636469 All rights reserved.
 
 This file is part of MacPatch, a program for installing and patching
 software.
 
 MacPatch is free software; you can redistribute it and/or modify it under
 the terms of the GNU General Public License (as published by the Free
 Software Foundation) version 2, dated June 1991.
 
 MacPatch is distributed in the hope that it will be useful, but WITHOUT ANY
 WARRANTY; without even the IMPLIED WARRANTY OF MERCHANTABILITY or FITNESS
 FOR A PARTICULAR PURPOSE. See the terms and conditions of the GNU General Public
 License for more details.
 
 You should have received a copy of the GNU General Public License along
 with MacPatch; if not, write to the Free Software Foundation, Inc.,
 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
'''


import json
import os
import sys
import plistlib
import subprocess
import urllib2
import ssl
import hashlib

ctx = ssl.create_default_context()
ctx.check_hostname = False
ctx.verify_mode = ssl.CERT_NONE

from distutils.version import LooseVersion, StrictVersion
from datetime import datetime, timedelta
import logging

logger = logging.getLogger(__name__)
logger.setLevel(logging.INFO)

# create a file handler
handler = logging.FileHandler('/Library/Logs/mp_planb.log')
handler.setLevel(logging.INFO)

# create a logging format
formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
handler.setFormatter(formatter)

# add the handlers to the logger
logger.addHandler(handler)

# Global Settings
MINAGENTVER="3.3.0.2"
DAYSRANGE=15
IGNORE_SSL=True
ISBETA=False
MPSERVER="localhost"
MPHASH="0"

def hasAgent():
	if not os.path.exists('/Library/MacPatch/Client/MPAgent'):
		return False
	else:
		return True

def hasMinVersion():
	mpVerPlist = plistlib.readPlist("/Library/MacPatch/Client/.mpVersion.plist")
	currentVersion = mpVerPlist['version'] +"."+ mpVerPlist['build']
	if LooseVersion(MINAGENTVER) > LooseVersion(currentVersion):
		logger.error('Failed Min Version, min=%s, found=%s',MINAGENTVER,currentVersion)
		return False
	else:
		return True

def hasCheckedIn(clientID):
	result = True
	if IGNORE_SSL:
		response = urllib2.urlopen('https://'+MPSERVER+':3600/api/v1/client/checkin/info/'+clientID, context=ctx)
	else:
		response = urllib2.urlopen('https://'+MPSERVER+':3600/api/v1/client/checkin/info/'+clientID)

	data = json.load(response)   
	if 'result' in data:
		mdate = data['result']['mdate2']
		if mdate:
			# 08/03/2018 14:34:35
			mdateStr=mdate.split()[0] # split to 08/03/2018
			datetime_object = datetime.strptime(mdateStr, '%m/%d/%Y')
			now = datetime.now()
			if now-timedelta(days=DAYSRANGE) <= datetime_object:
				result = True
			else:
				logger.error('Failed Checkin, lastdate=%s',mdate)
				logger.error('Todays date=%s',mdate)
				result = False

	return result

def clientID():
	# IOPlatformUUID
	plist_data_raw = subprocess.check_output(["ioreg", "-rd1", "-c", "IOPlatformExpertDevice", "-a"])
	plist_data = plistlib.readPlistFromString(plist_data_raw)
	return plist_data[0]['IOPlatformUUID']

def checkSettingsFile():
	plistPath = '/Users/Shared/.mpPlanB.plist'
	if os.path.exists(plistPath):
		mpPlanbPlist = plistlib.readPlist(plistPath)
		if 'minversion' in mpPlanbPlist:
			MINAGENTVER = mpPlanbPlist['minversion']
		if 'daysrange' in mpPlanbPlist:
			DAYSRANGE = mpPlanbPlist['daysrange']
		if 'mpserver' in mpPlanbPlist:
			MPSERVER = mpPlanbPlist['mpserver']
		if 'ignoressl' in mpPlanbPlist:
			IGNORE_SSL = mpPlanbPlist['ignoressl']

def validAgentHash():
    if MPHASH == '0':
        # Hash Has not been configured
        return True

    hash_md5 = hashlib.md5()
    with open('/Library/MacPatch/Client/MPAgent', "rb") as f:
        for chunk in iter(lambda: f.read(4096), b""):
            hash_md5.update(chunk)
    
    if hash_md5.hexdigest().lower() == MPHASH.lower():
        return True
    else:
        return False

def main():
	logger.info("Running MacPatch planb checks.")
	runPlanB = 0
	checkSettingsFile()
	cid = clientID()
	if hasAgent() == False:
		logger.error("Failed Agent Check")
		runPlanB = runPlanB + 1

	if hasMinVersion() == False:
		logger.error("Failed Min Version")
		runPlanB = runPlanB + 1

	if hasCheckedIn(cid) == False:
		logger.error("Failed Checkin")
		runPlanB = runPlanB + 1

	if validAgentHash() == False:
		logger.error("Failed Agent Hash Check")
		runPlanB = runPlanB + 1

	if runPlanB > 0:
		logger.error("Checks failed, need to run plan b.")
		planBRes = subprocess.check_output(["/usr/local/sbin/planb"])
		logger.info(planBRes)
	else:
		logger.info("No update needed.")

if __name__ == '__main__':
	main()	