#!/bin/bash
#
# MPTomcatSite
#
# chkconfig: 2345 96 96
# description: 	Start up the Apache Tomcat server.

# Source function library.
. /etc/init.d/functions

if [ -d  "/usr/lib/jvm/default-java" ]; then
	export JAVA_HOME=/usr/lib/jvm/default-java
elif [ -d  "/usr/lib/jvm/java" ]; then
	export JAVA_HOME=/usr/lib/jvm/java
fi	
export PATH=$JAVA_HOME/bin:$PATH
TOMCAT_HOME=/Library/MacPatch/Server/tomcat-mpsite
SHUTDOWN_WAIT=20
 
start() 
{
	# Start tomcat
	echo "Starting tomcat"
	ulimit -n 100000
	umask 022
	/bin/su -p -s /bin/sh www-data $TOMCAT_HOME/bin/startup.sh
}
 
stop() 
{
	# Stop tomcat
	echo "Stoping Tomcat"
	/bin/su -p -s /bin/sh www-data $TOMCAT_HOME/bin/shutdown.sh
}
 
case $1 in
start)
	start
	;;
stop)
	stop
	;;
restart)
	stop
	start
	;;
*) 
	echo "Run as $0 <start|stop|restart>"
	exit 1
	;; 
esac
exit 0
