site_name: MacPatch v3.1
pages:
    - Home: index.md
    - Installation:
        - Server Install & Setup: server_install.md
        - Client Build & Upload: client_build_install.md
    - Admin Console:
        - User Accounts: user_accounts.md
        - Patching:
            - Apple Patches: apple_patches.md
            - Custom Patches: custom_patches.md
            - Patch Groups: patch_groups.md
        - Software:
            - Groups: sw_groups.md
            - Tasks: sw_tasks.md
            - Packages: sw_packages.md
        - OS Management:
            - Profiles: profiles.md
    - About:
        - License: 'about/license.md'

theme:
    name: readthedocs

extra_css: [ 'css/extra.css' ]
use_directory_urls: false
