#!/bin/sh

# ***************************************************************************************
# PreFlight Script for MacPatch Client Installer
# ver 1.7
# Created By Charles Heizer
# LLNL
#
#
# ***************************************************************************************

systemVersion=`/usr/bin/sw_vers -productVersion`
majorVer=`echo $systemVersion | cut -d . -f 1,2  | sed 's/\.//g'`
minorVer=`echo $systemVersion | cut -d . -f 2`
buildVer=`echo $systemVersion | cut -d . -f 3`

# Script Parent Dir Path
SRC=$(cd $(dirname "$0"); pwd)

MPBaseDir="/Library/MacPatch"
MPClientDir="${MPBaseDir}/Client"
dts=`date +%Y%m%d%H%M%S`
usrID="NULL"
if [ -e "${SRC}/ccusr" ]; then
	usrID=`${SRC}/ccusr`
fi


# ***************************************************************************************
# Kill the running MP processes

# Launch Daemons
if [ -f "/Library/LaunchDaemons/gov.llnl.mp.agent.plist" ]; then	
	/bin/launchctl remove gov.llnl.mp.agent
	sleep 2
	/bin/launchctl unload /Library/LaunchDaemons/gov.llnl.mp.agent.plist
	sleep 2
	
	rm /Library/LaunchDaemons/gov.llnl.mp.agent.plist
fi

if [ -f "/Library/LaunchDaemons/gov.llnl.mp.worker.plist" ]; then	
	/bin/launchctl remove gov.llnl.mp.worker
	sleep 2
	/bin/launchctl unload /Library/LaunchDaemons/gov.llnl.mp.worker.plist
	sleep 2
	
	rm /Library/LaunchDaemons/gov.llnl.mp.worker.plist
fi	

# Launch Agents

# Old Clean up for now ...
if [ -f "/Library/LaunchAgents/gov.llnl.mpRBWatcher.plist" ]; then
	if [ "$usrID" != "NULL" ]; then
		chroot -u $usrID / /bin/launchctl unload /Library/LaunchAgents/gov.llnl.mpRBWatcher.plist
	fi	
	
	rm /Library/LaunchAgents/gov.llnl.mpRBWatcher.plist
fi

if [ -f "/Library/LaunchAgents/gov.llnl.MPRebootD.plist" ]; then
	if [ "$usrID" != "NULL" ]; then
		chroot -u $usrID / /bin/launchctl unload /Library/LaunchAgents/gov.llnl.MPRebootD.plist
	fi	
	
	rm /Library/LaunchAgents/gov.llnl.MPRebootD.plist
fi

if [ -f "/Library/LaunchAgents/gov.llnl.mp.status.plist" ]; then
	if [ "$usrID" != "NULL" ]; then
		chroot -u $usrID / /bin/launchctl unload /Library/LaunchAgents/gov.llnl.mp.status.plist
	fi
	
	rm /Library/LaunchAgents/gov.llnl.mp.status.plist
fi

# ***************************************************************************************
# MacPatch Pre-Deployment
#

# Remove the temp Migration Dir if exists
if [ -d "/private/tmp/MPMigration" ]; then
	rm -rf "/private/tmp/MPMigration"
fi
mkdir -p "/private/tmp/MPMigration"

if [ -f "/Library/MacPatch/Client/.tasks/gov.llnl.mp.tasks.plist" ]; then
	cp "/Library/MacPatch/Client/.tasks/gov.llnl.mp.tasks.plist" "/private/tmp/MPMigration/gov.llnl.mp.tasks.plist"
fi	

# Framework
if [ -d "/Library/Frameworks/MPFramework.framework" ]; then	
	rm -rf "/Library/Frameworks/MPFramework.framework"
fi	

# AuthPlugin
ClearAuthDB=0
if [ -d "/System/Library/CoreServices/SecurityAgentPlugins/MPAuthPlugin.bundle" ]; then	
	rm -rf "/System/Library/CoreServices/SecurityAgentPlugins/MPAuthPlugin.bundle"
	ClearAuthDB=1
fi	

if [ -f "$MPClientDir/MPAuthPluginTool" ]; then	
	"$MPClientDir/MPAuthPluginTool" -d
else
	# We do this to prevent issues with the system not 
	# booting properly
	if [ $ClearAuthDB == 1 ]; then
		rm /private/var/db/auth.db
	fi
fi	

if [ -d "$MPClientDir" ]; then
	echo "Removing $MPClientDir"
	rm -rf "$MPClientDir"
fi

# Clean up old downloads
if [ -d "/Library/Application Support/MacPatch/SW_Data/sw" ]; then
	rm -rf /Library/Application\ Support/MacPatch/SW_Data/sw/*
fi

# Remove Old Crash Reports
find /Library/Logs -type f -name "MP*.crash" -exec rm -f {} \;

exit 0