"""0007 - Base

Revision ID: 100007
Revises: 100006a
Create Date: 2018-04-18

"""

# revision identifiers, used by Alembic.
revision = '100007'
down_revision = '100006a'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


def upgrade():
	### commands auto generated by Alembic - please adjust! ###

	### end Alembic commands ###
	u_qstr1="ALTER TABLE `mp_patches` ADD COLUMN `pkg_useS3` int(1) NULL DEFAULT 0 AFTER `pkg_env_var`, ADD COLUMN `pkg_S3path` varchar(255) NULL AFTER `pkg_useS3`;"
	op.execute(u_qstr1)



def downgrade():
	### commands auto generated by Alembic - please adjust! ###

	### end Alembic commands ###
	d_qstr1 = "ALTER TABLE `mp_patches` DROP COLUMN `pkg_S3path`, DROP COLUMN `pkg_useS3`;"
	op.execute(d_qstr1)
