"""00013 - Base

Revision ID: 100013
Revises: 100012
Create Date: 2020-09-08

"""

# revision identifiers, used by Alembic.
revision = '100013'
down_revision = '100012'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


def upgrade():
	### commands auto generated by Alembic - please adjust! ###
	op.create_table('mp_provision_script',
					sa.Column('rid', sa.BigInteger(), nullable=False, autoincrement=True),
					sa.Column('sid', sa.String(length=50), nullable=False),
					sa.Column('name', sa.String(length=255), nullable=False),
					sa.Column('script', mysql.TEXT(), nullable=False),
					sa.Column('active', sa.Integer(), server_default='0', nullable=True),
					sa.Column('scope', sa.Integer(), server_default='0', nullable=True),
					sa.Column('type', sa.Integer(), server_default='1', nullable=True),
					sa.Column('order', sa.Integer(), server_default='99', nullable=True),
					sa.Column('sw_start_datetime', sa.DateTime(), server_default='1970-01-01 00:00:00', nullable=True),
					sa.Column('sw_end_datetime', sa.DateTime(), server_default='1970-01-01 00:00:00', nullable=True),
					sa.Column('mdate', sa.DateTime(), server_default='1970-01-01 00:00:00', nullable=True),
					sa.PrimaryKeyConstraint('rid')
					)
	op.create_index(op.f('ix_mp_provision_task_sid'), 'mp_provision_script', ['sid'], unique=False)

	### end Alembic commands ###


def downgrade():
	### commands auto generated by Alembic - please adjust! ###
	op.drop_index(op.f('ix_mp_provision_task_sid'), table_name='mp_provision_script')
	op.drop_table('mp_provision_script')

	### end Alembic commands ###