"""00016 - Base

Revision ID: 100016
Revises: 100014
Create Date: 2026-05-18

"""

# revision identifiers, used by Alembic.
revision = '100016'
down_revision = '100015'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


def upgrade():
	### commands auto generated by Alembic - please adjust! ###

	op.create_table('mp_client_settings_v2',
		sa.Column('rid', sa.BigInteger(), nullable=False, autoincrement=True),
		sa.Column('group_id', sa.String(length=50), nullable=False),
		sa.Column('data', mysql.TEXT(), nullable=False),
		sa.Column('data64', mysql.TEXT(), nullable=False),
		sa.Column('mdate', sa.DateTime(), server_default='1970-01-01 00:00:00', nullable=True),
		sa.PrimaryKeyConstraint('rid')
	)

	### end Alembic commands ###


def downgrade():
	### commands auto generated by Alembic - please adjust! ###
	op.drop_table('mp_client_settings_v2')

	### end Alembic commands ###