"""0005 - MP 3.1.2 Schema additions

Revision ID: 100005
Revises: 100004
Create Date: 2018-12-18

"""

# revision identifiers, used by Alembic.
revision = '100005'
down_revision = '100004'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


def upgrade():
	### commands auto generated by Alembic - please adjust! ###

	op.create_table('mp_inv_errors',
		sa.Column('rid', sa.BigInteger(), nullable=False, autoincrement=True),
		sa.Column('cuuid', sa.String(length=50), server_default='', nullable=False),
		sa.Column('inv_table', sa.String(length=255), nullable=False),
		sa.Column('error_msg', mysql.TEXT(), nullable=True),
		sa.Column('json_data', mysql.LONGTEXT(), nullable=True),
		sa.Column('mdate', sa.DateTime(), server_default='1970-01-01 00:00:00', nullable=True),
		sa.PrimaryKeyConstraint('rid')
	)
	op.create_index(op.f('ix_mp_inv_errors_cuuid'), 'mp_inv_errors', ['cuuid'], unique=False)

	op.create_table('mp_inv_log',
		sa.Column('rid', sa.BigInteger(), nullable=False, autoincrement=True),
		sa.Column('cuuid', sa.String(length=50), server_default='', nullable=False),
		sa.Column('mp_server', sa.String(length=255), nullable=False),
		sa.Column('inv_table', sa.String(length=255), nullable=False),
		sa.Column('error_no', sa.String(length=10), nullable=True),
		sa.Column('error_msg', mysql.TEXT(), nullable=True),
		sa.Column('json_data', mysql.LONGTEXT(), nullable=True),
		sa.Column('mdate', sa.DateTime(), server_default='1970-01-01 00:00:00', nullable=True),
		sa.PrimaryKeyConstraint('rid')
	)
	op.create_index(op.f('ix_mp_inv_log_cuuid'), 'mp_inv_log', ['cuuid'], unique=False)

def downgrade():
	### commands auto generated by Alembic - please adjust! ###
	op.drop_index(op.f('ix_mp_inv_log_cuuid'), table_name='mp_inv_log')
	op.drop_table('mp_inv_log')

	op.drop_index(op.f('ix_mp_inv_errors_cuuid'), table_name='mp_inv_errors')
	op.drop_table('mp_inv_errors')
